### ISSUE TITLE
Change instruction on npmjs.com

### ISSUE THREAD

**Issue by aimyth** [robtweed/qewd-transform-json#10]
Thanks for the great package.
The instructions at 
https://www.npmjs.com/package/qewd-transform-json

`npm install qewd-transform-JSON`
needs to be changed to 
`npm install qewd-transform-json`

As npm no longer supports capital case package names . 

<pre>
`npm ERR! code E404  
npm ERR! 404 Not Found - GET https://registry.npmjs.org/qewd-transform-JSON - Not found  
npm ERR! 404   
npm ERR! 404  'qewd-transform-JSON@latest' is not in the npm registry  
npm ERR! 404 Your package name is not valid, because  
npm ERR! 404  1. name can no longer contain capital letters`  
</pre>

**Comment by robtweed** [comment]
Fixed.  Many thanks for letting me know!
