### ISSUE TITLE
Add a transform method for async

### ISSUE THREAD

**Issue by aimyth** [robtweed/qewd-transform-json#11]
Since the string manipulation operations tends to be heavy as the object increases, can a async method be written too for those transforms that are heavy.

**Comment by robtweed** [comment]
I think it would be tricky to do this without a major change to the logic.  

I actually built this module for use within the Node.js run-time environment provided by QEWD (https://github.com/robtweed/qewd), in which concurrency isn't an issue - see https://medium.com/the-node-js-collection/having-your-node-js-cake-and-eating-it-too-799e90d40186  for more background on the thinking behind the QEWD environment.  In the QEWD run-time container, it doesn't matter how time and CPU-consuming the transformation takes.

I'm more than happy for someone else to figure out an async version of a qewd-transform-json fork, but, given what I've said about QEWD, which is where I use it, I'm afraid I have other priorities.

Thanks for your interest however! :-)

**Comment by aimyth** [comment]
Sure thanks..
