### ISSUE TITLE
Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by TejasRamane** [robtweed/qewd-transform-json#3]
When trying to transform any json i get the above mentioned error. I get the same error while running test.js. This is becasue the helpers in the transform function is undefined. Could you please resolve this or let me know if i am doing something wrong.

**Comment by robtweed** [comment]
Try the latest version (1.9) that I've pushed out now - should fix this issue, but let me know if you get any further problems

**Comment by TejasRamane** [comment]
Thank you @robtweed  the fix seem to have resolved the issue.
